name: ayman_package
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.2

  # loading UI Packages
  percent_indicator: ^4.2.3
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.0

  # Responsive UI
  flutter_screenutil: ^5.9.0
  responsive_framework: ^1.1.1

  # Animations
  lottie: ^2.6.0

  # Helper 
  equatable: ^2.0.5
  dartz: ^0.10.1
  go_router: ^11.0.0
  restart_app: ^1.2.1
  
  # state managment
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  
  
  flutter_native_splash: ^2.3.2
  http: ^1.1.0
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.2
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.0
  build_runner: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  
flutter_native_splash:
  color: "#ffffff"
  image:  assets/images/picture.jpg
  branding:  assets/images/picture.jpg
  color_dark: "#121212"
  image_dark: assets/images/picture.jpg
  branding_dark:  assets/images/picture.jpg

  android_12:
    image: assets/images/picture.jpg
    icon_background_color: "#ffffff"
    image_dark:  assets/images/picture.jpg
    icon_background_color_dark: "#121212"

  





  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
